"""rename address to location

Revision ID: 026488e1c210
Revises: 48c91b24f47e
Create Date: 2025-12-23 10:04:43.879531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026488e1c210'
down_revision = '48c91b24f47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
